### ISSUE TITLE
Add Tuff to the mechanical extruder recipe

### ISSUE THREAD

**Issue by Zand-MC** [SinmisModdingCommunity/The_Createville_Server#53]
Add the Tuff recipe to the mechanical extruder or the CustomCobbleGen mod. Please

**Comment by SinmisModdingCommunity** [comment]
I don't know how you people stay out of format but I have a comment about why this feature wasn't added in one of the last updates. This feature is overpowered at the current state because you can crush the tuff in the crushing wheels and get quite a lot of resources easily which I kinda want to avoid so if this ends up getting added it will provide some basic resource automation but it will be best for building and not for resource gathering

**Comment by Zand-MC** [comment]
The Gold and iron could be removed tbh the point is to be able to have a renewable zinc and copper source
